-- ============================================================
-- Drug Tracking System — PostgreSQL Table Creation Scripts
-- Destination: Azure PostgreSQL
-- Schema version: new ERD (MainDB)
-- ============================================================
--
-- CHANGES FROM PREVIOUS VERSION
-- ────────────────────────────────────────────────────────────
-- drug_categories : PK renamed category_id → id
--                   Added: description, created_at
--
-- drugs           : PK renamed drug_id → id
--                   Column renamed: active_ingredient → active_substance
--                   Added: dosage_form, strength, manufacturer,
--                          image_url, created_at, updated_at
--                   FK updated: → drug_categories(id)
--
-- drug_alternatives: FKs updated: → drugs(id)
--
-- pharmacy_inventory (was drug_prices):
--                   Table renamed
--                   Removed: available
--                   Added: quantity, minimum_stock
--                   FK updated: → drugs(id)
--                   FK added:   → pharmacies(id)
--                   id changed: BIGINT → BIGSERIAL
--                   (see note below on why this changed)
--
-- price_history   : FK updated: → drugs(id)
-- drug_analytics  : FK updated: → drugs(id)
-- availability_history: FK updated: → drugs(id)
--
-- All indexes renamed / replaced accordingly.
--
-- BUGFIX (post-deployment): pharmacy_inventory.id was originally BIGINT,
-- with the value supplied by dbt via ROW_NUMBER() OVER (ORDER BY
-- pharmacy_id, drug_id) in core_pharmacy_inventory.sql. This ID is
-- recalculated from 1 on every dbt run, scoped only to the batch of
-- pharmacy files ingested in that run (since old seed files are cleaned
-- up between runs — see storage_ingestion.py / datalake_archive design).
-- Two different runs can therefore assign the same id to two different
-- (pharmacy_id, drug_id) pairs, causing:
--   UniqueViolation: duplicate key value violates unique constraint
--   "pharmacy_inventory_pkey"
-- on upsert, since the upsert's conflict key is (drug_id, pharmacy_id),
-- not id — so a new pair with a colliding id attempts a fresh INSERT
-- instead of an UPDATE, and collides with an id already assigned in a
-- previous run.
--
-- FIX: id is now BIGSERIAL, auto-generated by PostgreSQL on first
-- insert and left untouched on every subsequent update. dbt's internal
-- ROW_NUMBER() id in core_pharmacy_inventory is still fine to keep for
-- DuckDB-internal uniqueness, but push_to_postgres.py must no longer
-- forward that column when upserting this table — see push_to_postgres.py
-- for the corresponding change.
-- ============================================================


-- ────────────────────────────────────────────
-- 1. DRUG_CATEGORIES
-- Must be created before DRUGS (FK dependency)
-- ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS drug_categories (
    id              BIGINT          PRIMARY KEY,
    name            VARCHAR(100)    NOT NULL UNIQUE,
    description     TEXT,
    created_at      TIMESTAMP
);


-- ────────────────────────────────────────────
-- 2. DRUGS
-- Master reference table for all drugs in the system
-- ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS drugs (
    id                  BIGINT          PRIMARY KEY,
    name                VARCHAR(255)    NOT NULL UNIQUE,
    active_substance    VARCHAR(255),
    category_id         BIGINT          REFERENCES drug_categories(id),
    dosage_form         VARCHAR(255),
    strength            VARCHAR(100),
    manufacturer        VARCHAR(255),
    description         TEXT,
    image_url           TEXT,
    created_at          TIMESTAMP,
    updated_at          TIMESTAMP
);


-- ────────────────────────────────────────────
-- 3. DRUG_ALTERNATIVES
-- Maps each drug to its alternatives (many-to-many)
-- ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS drug_alternatives (
    id                      BIGINT  PRIMARY KEY,
    drug_id                 BIGINT  NOT NULL REFERENCES drugs(id),
    alternative_drug_id     BIGINT  NOT NULL REFERENCES drugs(id),
    -- Prevent duplicate alternative pairs
    CONSTRAINT unique_alternative   UNIQUE (drug_id, alternative_drug_id),
    -- Prevent a drug from being its own alternative
    CONSTRAINT no_self_alternative  CHECK  (drug_id != alternative_drug_id)
);


-- ────────────────────────────────────────────
-- 4. PHARMACY_INVENTORY
-- Holds each pharmacy's drug stock, pricing, and quantity.
-- Replaces the old drug_prices table.
-- ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS pharmacy_inventory (
    id              BIGSERIAL       PRIMARY KEY,
    pharmacy_id     BIGINT          NOT NULL REFERENCES pharmacies(id),
    drug_id         BIGINT          NOT NULL REFERENCES drugs(id),
    quantity        INT             NOT NULL DEFAULT 0 CHECK (quantity >= 0),
    minimum_stock   INT             NOT NULL DEFAULT 0 CHECK (minimum_stock >= 0),
    price           NUMERIC(10, 2)  NOT NULL CHECK (price >= 0),
    last_updated    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Each pharmacy can only have one record per drug
    CONSTRAINT unique_pharmacy_drug UNIQUE (pharmacy_id, drug_id)
);


-- ────────────────────────────────────────────
-- 5. PRICE_HISTORY
-- Tracks price changes over time per drug per pharmacy
-- Populated by dbt snapshot on every pipeline run
-- ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS price_history (
    id              BIGINT          PRIMARY KEY,
    drug_id         BIGINT          NOT NULL REFERENCES drugs(id),
    pharmacy_id     BIGINT          NOT NULL,
    price           NUMERIC(10, 2)  NOT NULL CHECK (price >= 0),
    recorded_at     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- ────────────────────────────────────────────
-- 6. DRUG_ANALYTICS
-- Aggregated analytics per drug
-- Computed by dbt on every pipeline run
-- Used when a patient searches for a specific drug (FR-8)
-- ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS drug_analytics (
    id                      BIGINT          PRIMARY KEY,
    drug_id                 BIGINT          NOT NULL REFERENCES drugs(id) UNIQUE,
    avg_price               NUMERIC(10, 2),
    min_price               NUMERIC(10, 2),
    max_price               NUMERIC(10, 2),
    availability_percentage NUMERIC(5, 2)   CHECK (
                                availability_percentage >= 0
                                AND availability_percentage <= 100
                            ),
    calculated_at           TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- ────────────────────────────────────────────
-- 7. AVAILABILITY_HISTORY
-- Tracks availability changes over time per drug per pharmacy
-- "available" is derived from pharmacy_inventory: quantity > 0
-- Used for deep analytics and demand rate calculation
-- ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS availability_history (
    id              BIGINT      PRIMARY KEY,
    drug_id         BIGINT      NOT NULL REFERENCES drugs(id),
    pharmacy_id     BIGINT      NOT NULL,
    available       BOOLEAN     NOT NULL,
    checked_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- ────────────────────────────────────────────
-- INDEXES
-- Improve query performance for common lookups
-- ────────────────────────────────────────────

-- Drug lookups by name and category
CREATE INDEX IF NOT EXISTS idx_drugs_name                   ON drugs(name);
CREATE INDEX IF NOT EXISTS idx_drugs_category               ON drugs(category_id);

-- Inventory lookups by pharmacy and drug
CREATE INDEX IF NOT EXISTS idx_pharmacy_inventory_pharmacy  ON pharmacy_inventory(pharmacy_id);
CREATE INDEX IF NOT EXISTS idx_pharmacy_inventory_drug      ON pharmacy_inventory(drug_id);

-- Partial index for availability queries (replaces idx_drug_prices_available)
-- Covers the common case: "find pharmacies where drug X is in stock"
CREATE INDEX IF NOT EXISTS idx_pharmacy_inventory_in_stock
    ON pharmacy_inventory(drug_id, pharmacy_id)
    WHERE quantity > 0;

-- History lookups
CREATE INDEX IF NOT EXISTS idx_price_history_drug           ON price_history(drug_id);
CREATE INDEX IF NOT EXISTS idx_price_history_pharmacy       ON price_history(pharmacy_id);
CREATE INDEX IF NOT EXISTS idx_availability_history_drug    ON availability_history(drug_id);
CREATE INDEX IF NOT EXISTS idx_availability_history_pharmacy ON availability_history(pharmacy_id);

-- Analytics lookup
CREATE INDEX IF NOT EXISTS idx_drug_analytics_drug          ON drug_analytics(drug_id);
