-- models/analytics/drug_analytics.sql
-- Builds the drug_analytics table
-- Computes per-drug price and availability statistics
-- across all pharmacies that carry each drug
--
-- Source:  core_pharmacy_inventory
-- Feeds:   drug_analytics table in PostgreSQL (FR-8: patient drug search)
--
-- Availability rule: a pharmacy is counted as "having the drug available"
--                    when quantity > 0  (confirmed derivation rule, new ERD)
--
-- One row per drug — drug_id carries a UNIQUE constraint in PostgreSQL.
-- id is a synthetic PK generated by ROW_NUMBER().

WITH inventory AS (
    SELECT * FROM {{ ref('core_pharmacy_inventory') }}
),

per_drug AS (
    SELECT
        drug_id,

        ROUND(AVG(price), 2)                AS avg_price,
        ROUND(MIN(price), 2)                AS min_price,
        ROUND(MAX(price), 2)                AS max_price,

        -- Percentage of pharmacies carrying this drug where stock > 0
        -- Numerator:   pharmacies with quantity > 0
        -- Denominator: all pharmacies carrying this drug (any quantity)
        ROUND(
            100.0
            * SUM(CASE WHEN quantity > 0 THEN 1 ELSE 0 END)
            / COUNT(*),
            2
        )                                   AS availability_percentage,

        CURRENT_TIMESTAMP                   AS calculated_at

    FROM inventory
    GROUP BY drug_id
)

SELECT
    ROW_NUMBER() OVER (
        ORDER BY drug_id
    )               AS id,
    drug_id,
    avg_price,
    min_price,
    max_price,
    availability_percentage,
    calculated_at

FROM per_drug
