# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t9tIfjGxvif8EAAqc0giQ_yE7W-cvN6A
"""

pip install boto3

import boto3

s3 = boto3.client(
    service_name="s3",
    endpoint_url="https://s3.us-east-005.backblazeb2.com",
    aws_access_key_id="0057034b0b8248e0000000001",
    aws_secret_access_key="K005DnwCqFlnsv41kJIREOHF4MsEiE8"
)

response = s3.list_objects_v2(
    Bucket='DEPI-data-lake'
)

print(response)

response = s3.list_objects_v2(
    Bucket='DEPI-data-lake',
    Delimiter='/'
)

# print(response)
response = s3.list_objects_v2(
    Bucket='DEPI-data-lake',
    Prefix='raw/pharmacies/',
    Delimiter='/'
)

for folder in response.get('CommonPrefixes', []):
    print(folder['Prefix'])

"""pharmacies Names"""

response = s3.list_objects_v2(
    Bucket='DEPI-data-lake'
)

for obj in response.get('Contents', []):
    print(obj['Key'])

s3.download_file(
    'DEPI-data-lake',
    'raw/pharmacies/chefaa/mom_baby.csv',
    'gardenia_Anthelmintics.csv'
)

"""*************
calculate the date
*************
"""

import os
import boto3
import pandas as pd

# =============================
# S3 Connection
# =============================



BUCKET = "DEPI-data-lake"

pharmacies = [
    "aldawaaegy",
    "bloom",
    "chefaa",
    "gardenia"
]

base_output = "downloads"

for pharmacy in pharmacies:

    print("=" * 60)
    print(f"Processing {pharmacy}")
    print("=" * 60)

    prefix = f"raw/pharmacies/{pharmacy}/"

    response = s3.list_objects_v2(
        Bucket=BUCKET,
        Prefix=prefix
    )

    csv_files = [
        obj["Key"]
        for obj in response.get("Contents", [])
        if obj["Key"].endswith(".csv")
    ]

    print(f"Found {len(csv_files)} files")

    output_folder = os.path.join(base_output, pharmacy)
    os.makedirs(output_folder, exist_ok=True)

    all_data = []

    for key in csv_files:

        filename = os.path.basename(key)
        local_file = os.path.join(output_folder, filename)

        print(f"Downloading: {filename}")

        s3.download_file(
            BUCKET,
            key,
            local_file
        )

        try:
            df = pd.read_csv(local_file)

            all_data.append(df)

        except Exception as e:
            print(f"Error reading {filename}: {e}")

        if os.path.exists(local_file):
            os.remove(local_file)

    if len(all_data) == 0:
        print(f"No data found for {pharmacy}")
        continue

    merged_df = pd.concat(all_data, ignore_index=True)

    output_file = os.path.join(
        output_folder,
        f"{pharmacy}_ALL.csv"
    )

    merged_df.to_csv(
        output_file,
        index=False,
        encoding="utf-8-sig"
    )

    print(f"Saved: {output_file}")
    print(f"Rows: {len(merged_df)}")

    del merged_df
    del all_data

print("\nAll pharmacies processed successfully.")

"""*************
cleaning data
*************

chefaa
"""

import os
import re
import pandas as pd
from urllib.parse import unquote
# ============================
# File Paths
# ============================

pharmacy = "chefaa"

input_file = f"downloads/{pharmacy}/{pharmacy}_ALL.csv"
output_file = f"downloads/{pharmacy}/{pharmacy}_CLEAN.csv"

# ============================
# Read CSV
# ============================

df = pd.read_csv(input_file)

print("Rows Before :", len(df))

# ======================================================
# Remove Unneeded Columns
# ======================================================

columns_to_drop = [
    "product_id",
    "url",
    "thumbnail_image",
    "availability",
    "specifications"
]

df.drop(
    columns=[c for c in columns_to_drop if c in df.columns],
    inplace=True
)

# ======================================================
# Rename Columns
# ======================================================

df.rename(columns={
    "name": "name_ar",
    "name_en": "name_en",
    "brand": "brand",
    "category": "category",
    "description": "description",
    "gallery_images": "gallery_images",
    "price": "price",
    "currency": "currency"
}, inplace=True)

# ======================================================
# Add Pharmacy Column
# ======================================================

df.insert(0, "pharmacy", pharmacy)

# ======================================================
# General Text Cleaning
# ======================================================

text_columns = [
    "name_ar",
    "name_en",
    "brand",
    "category",
    "description"
]

for col in text_columns:

    if col in df.columns:

        df[col] = (
            df[col]
            .fillna("")
            .astype(str)
            .str.replace("\n", " ", regex=False)
            .str.replace("\t", " ", regex=False)
            .str.replace("|", " ", regex=False)
            .str.replace(r"\s+", " ", regex=True)
            .str.strip()
        )

# ======================================================
# Clean Category
# Keep Last Category Only
# ======================================================

def clean_category(cat):

    if pd.isna(cat):
        return ""

    parts = [x.strip() for x in str(cat).split(">") if x.strip()]

    if len(parts):
        return parts[-1]

    return ""

df["category"] = df["category"].apply(clean_category)

# ======================================================
# Clean Description
# ======================================================

def clean_description(desc, brand):

    if pd.isna(desc):
        return ""

    desc = str(desc)

    # Remove repeated headings
    remove_words = [
        "مميزات المنتج",
        "عن هذا المنتج"
    ]

    for w in remove_words:
        desc = desc.replace(w, "")

    # Remove brand name
    if pd.notna(brand):

        brand = str(brand).strip()

        if brand != "":
            desc = re.sub(
                re.escape(brand),
                "",
                desc,
                flags=re.IGNORECASE
            )

    desc = re.sub(r"\s+", " ", desc)

    return desc.strip()

df["description"] = df.apply(
    lambda row: clean_description(
        row["description"],
        row["brand"]
    ),
    axis=1
)

# ======================================================
# Clean English Name
# ======================================================

def clean_name_en(name):

    if pd.isna(name):
        return ""

    # Decode URL Encoding
    name = unquote(str(name))

    name = name.lower()

    # remove product codes
    name = re.sub(r"\b[a-z0-9_]{4,}\b$", "", name)

    # remove sizes
    name = re.sub(
        r"\b\d+(\.\d+)?\s?(ml|gm|g|mg|kg|l|mcg)\b",
        "",
        name,
        flags=re.IGNORECASE
    )

    # remove extra spaces
    name = re.sub(r"\s+", " ", name)

    return name.strip()

df["name_en"] = df["name_en"].apply(clean_name_en)

# ======================================================
# Clean Brand
# ======================================================

df["brand"] = (
    df["brand"]
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

# ======================================================
# Price
# ======================================================

df["price"] = pd.to_numeric(
    df["price"],
    errors="coerce"
)

# ======================================================
# Remove Empty Names
# ======================================================

df = df[
    df["name_en"] != ""
]

# ======================================================
# Remove Duplicate Products
# ======================================================

df.drop_duplicates(
    subset=[
        "name_en",
        "brand",
        "price"
    ],
    inplace=True
)

# ======================================================
# Reorder Columns
# ======================================================

final_columns = [
    "pharmacy",
    "name_ar",
    "name_en",
    "brand",
    "category",
    "description",
    "gallery_images",
    "price",
    "currency"
]

df = df[final_columns]

# ======================================================
# Save
# ======================================================

os.makedirs(
    os.path.dirname(output_file),
    exist_ok=True
)

df.to_csv(
    output_file,
    index=False,
    encoding="utf-8-sig"
)

print("Rows After :", len(df))
print("Saved To :", output_file)

"""bloom"""

import os
import re
import html
import pandas as pd
from urllib.parse import unquote

# ==========================================
# SETTINGS
# ==========================================

PHARMACY = "bloom"

INPUT_FILE = "downloads/bloom/bloom_ALL.csv"
OUTPUT_FILE = "downloads/bloom/bloom_CLEAN.csv"

# ==========================================
# READ
# ==========================================

df = pd.read_csv(INPUT_FILE, low_memory=False)

print("Rows Before:", len(df))

# ==========================================
# KEEP ONLY NEEDED COLUMNS
# ==========================================

df = df[
    [
        "name_ar",
        "name_en",
        "vendor",
        "product_type",
        "description_ar",
        "description_en",
        "gallery_images",
        "price",
        "currency",
    ]
].copy()

# ==========================================
# RENAME
# ==========================================

df.rename(
    columns={
        "vendor": "brand",
        "product_type": "category",
    },
    inplace=True,
)

# ==========================================
# ADD PHARMACY
# ==========================================

df.insert(0, "pharmacy", PHARMACY)

# ==========================================
# TEXT CLEANER
# ==========================================

def clean_text(x):

    if pd.isna(x):
        return ""

    x = str(x)

    x = unquote(x)

    x = html.unescape(x)

    x = x.replace("\n", " ")
    x = x.replace("\r", " ")
    x = x.replace("\t", " ")

    x = re.sub(r"\s+", " ", x)

    return x.strip()

# ==========================================
# CLEAN ENGLISH NAME
# ==========================================

def clean_name_en(x):

    x = clean_text(x).lower()

    # remove url encoding leftovers
    x = re.sub(r"%[0-9a-fA-F]{2}", " ", x)

    # remove sizes
    x = re.sub(
        r"\b\d+(\.\d+)?\s*(ml|gm|mg|g|kg|l|mcg|oz|مل|جم)\b",
        "",
        x,
        flags=re.IGNORECASE,
    )

    # remove %
    x = re.sub(r"\d+%", "", x)

    # replace separators
    x = x.replace("-", " ")
    x = x.replace("_", " ")

    # remove random codes at end
    x = re.sub(r"\b[a-z0-9]{6,}\b$", "", x)

    x = re.sub(r"\s+", " ", x)

    return x.strip()

# ==========================================
# CLEAN DESCRIPTION
# ==========================================

def clean_description(x):

    x = clean_text(x)

    patterns = [

        r"How to use:.*",
        r"Ingredients:.*",

        r"طريقة الاستخدام:.*",
        r"كيفية الاستخدام:.*",
        r"مكونات:.*"

    ]

    for p in patterns:

        x = re.sub(
            p,
            "",
            x,
            flags=re.IGNORECASE | re.DOTALL,
        )

    x = re.sub(r"\s+", " ", x)

    return x.strip()

# ==========================================
# APPLY
# ==========================================

df["name_ar"] = df["name_ar"].apply(clean_text)

df["brand"] = df["brand"].apply(clean_text)

df["category"] = df["category"].apply(clean_text)

df["name_en"] = df["name_en"].apply(clean_name_en)

df["description_en"] = df["description_en"].apply(clean_description)

df["description_ar"] = df["description_ar"].apply(clean_description)

# ==========================================
# FIRST IMAGE ONLY
# ==========================================

def first_image(x):

    if pd.isna(x):
        return ""

    return str(x).split("|")[0].strip()

df["gallery_images"] = df["gallery_images"].apply(first_image)

# ==========================================
# PRICE
# ==========================================

df["price"] = pd.to_numeric(df["price"], errors="coerce")

# ==========================================
# REMOVE DUPLICATES
# ==========================================

df.drop_duplicates(
    subset=[
        "name_en",
        "brand",
        "price",
    ],
    inplace=True,
)

# ==========================================
# FINAL ORDER
# ==========================================

df = df[
    [
        "pharmacy",
        "name_ar",
        "name_en",
        "brand",
        "category",
        "description_ar",
        "description_en",
        "gallery_images",
        "price",
        "currency",
    ]
]

# ==========================================
# SAVE
# ==========================================

os.makedirs("downloads/bloom", exist_ok=True)

df.to_csv(
    OUTPUT_FILE,
    index=False,
    encoding="utf-8-sig",
)

print("Rows After:", len(df))
print("Saved:", OUTPUT_FILE)

"""gardenia"""

import os
import re
import html
import pandas as pd
from urllib.parse import unquote

# =====================================================
# SETTINGS
# =====================================================

PHARMACY = "gardenia"

INPUT_FILE = "downloads/gardenia/gardenia_ALL.csv"
OUTPUT_FILE = "downloads/gardenia/gardenia_CLEAN.csv"

# =====================================================
# READ
# =====================================================

df = pd.read_csv(INPUT_FILE, low_memory=False)

print("Rows Before:", len(df))

# =====================================================
# KEEP NEEDED COLUMNS
# =====================================================

df = df[
    [
        "name",
        "brand",
        "category",
        "description",
        "gallery_images",
        "price",
        "currency"
    ]
].copy()

# =====================================================
# RENAME
# =====================================================

df.rename(
    columns={
        "name": "name_en"
    },
    inplace=True
)

# =====================================================
# ADD PHARMACY
# =====================================================

df.insert(0, "pharmacy", PHARMACY)

# =====================================================
# GENERAL TEXT CLEANING
# =====================================================

def clean_text(text):

    if pd.isna(text):
        return ""

    text = str(text)

    text = unquote(text)

    text = html.unescape(text)

    text = text.replace("\n", " ")
    text = text.replace("\r", " ")
    text = text.replace("\t", " ")

    text = re.sub(r"\s+", " ", text)

    return text.strip()

# =====================================================
# CLEAN PRODUCT NAME
# =====================================================

def clean_name(name):

    name = clean_text(name)

    name = name.lower()

    # remove url encoding leftovers
    name = re.sub(r"%[0-9A-Fa-f]{2}", " ", name)

    # remove sizes
    name = re.sub(
        r"\b\d+(\.\d+)?\s*(ml|gm|mg|g|kg|l|mcg|oz|caps|tab|pcs)\b",
        "",
        name,
        flags=re.IGNORECASE
    )

    # remove percentages
    name = re.sub(r"\d+%", "", name)

    # remove separators
    name = name.replace("-", " ")
    name = name.replace("_", " ")

    # remove extra spaces
    name = re.sub(r"\s+", " ", name)

    return name.strip()

# =====================================================
# EXTRACT BRAND
# =====================================================

def extract_brand(row):

    brand = clean_text(row["brand"])

    if brand != "":
        return brand

    words = clean_name(row["name_en"]).split()

    if len(words) == 0:
        return ""

    # أول كلمة غالباً هى البراند
    return words[0].title()

# =====================================================
# CLEAN DESCRIPTION
# =====================================================

def clean_description(desc):

    desc = clean_text(desc)

    # remove duplicate lines
    parts = []

    for line in desc.split("."):

        line = line.strip()

        if line and line not in parts:
            parts.append(line)

    desc = ". ".join(parts)

    # remove headings
    patterns = [

        r"how to use:.*",
        r"ingredients:.*",

        r"contents hide.*"

    ]

    for p in patterns:

        desc = re.sub(
            p,
            "",
            desc,
            flags=re.IGNORECASE | re.DOTALL
        )

    desc = re.sub(r"\s+", " ", desc)

    return desc.strip()

# =====================================================
# APPLY
# =====================================================

df["name_en"] = df["name_en"].apply(clean_name)

df["brand"] = df.apply(extract_brand, axis=1)

df["category"] = df["category"].apply(clean_text)

df["description"] = df["description"].apply(clean_description)

# =====================================================
# KEEP FIRST IMAGE ONLY
# =====================================================

def first_image(img):

    if pd.isna(img):
        return ""

    return str(img).split("|")[0].strip()

df["gallery_images"] = df["gallery_images"].apply(first_image)

# =====================================================
# PRICE
# =====================================================

df["price"] = pd.to_numeric(
    df["price"],
    errors="coerce"
)

# =====================================================
# REMOVE DUPLICATES
# =====================================================

df.drop_duplicates(
    subset=[
        "name_en",
        "brand",
        "price"
    ],
    inplace=True
)

# =====================================================
# REMOVE EMPTY NAMES
# =====================================================

df = df[df["name_en"] != ""]

# =====================================================
# FINAL ORDER
# =====================================================

df = df[
    [
        "pharmacy",
        "name_en",
        "brand",
        "category",
        "description",
        "gallery_images",
        "price",
        "currency"
    ]
]

# =====================================================
# SAVE
# =====================================================

os.makedirs(
    "downloads/gardenia",
    exist_ok=True
)

df.to_csv(
    OUTPUT_FILE,
    index=False,
    encoding="utf-8-sig"
)

print()

print("Rows After:", len(df))

print("Saved:", OUTPUT_FILE)

"""aldawaaegy"""

import os
import re
import html
import pandas as pd
from urllib.parse import unquote

# ==========================================
# SETTINGS
# ==========================================

PHARMACY = "aldawaaegy"

INPUT_FILE = "downloads/aldawaaegy/aldawaaegy_ALL.csv"
OUTPUT_FILE = "downloads/aldawaaegy/aldawaaegy_CLEAN.csv"

# ==========================================
# READ
# ==========================================

df = pd.read_csv(INPUT_FILE, low_memory=False)

print("Rows Before:", len(df))

# ==========================================
# KEEP REQUIRED COLUMNS
# ==========================================

df = df[
    [
        "name",
        "brand",
        "Category",
        "description",
        "gallery_images",
        "price",
        "currency"
    ]
].copy()

# ==========================================
# RENAME
# ==========================================

df.rename(columns={
    "name": "name_en",
    "Category": "category"
}, inplace=True)

# ==========================================
# ADD PHARMACY
# ==========================================

df.insert(0, "pharmacy", PHARMACY)

# ==========================================
# GENERAL TEXT CLEANER
# ==========================================

def clean_text(text):

    if pd.isna(text):
        return ""

    text = str(text)

    text = unquote(text)

    text = html.unescape(text)

    text = text.replace("\n", " ")
    text = text.replace("\r", " ")
    text = text.replace("\t", " ")

    text = re.sub(r"\s+", " ", text)

    return text.strip()

# ==========================================
# CLEAN PRODUCT NAME
# ==========================================

def clean_name(name):

    name = clean_text(name).lower()

    # Remove URL encoded leftovers
    name = re.sub(r"%[0-9a-fA-F]{2}", " ", name)

    # Remove sizes
    name = re.sub(
        r"\b\d+(\.\d+)?\s*(ml|gm|mg|g|kg|l|mcg|oz|caps|cap|tablet|tablets|tab|pcs|pack|مل|جم)\b",
        "",
        name,
        flags=re.IGNORECASE
    )

    # Remove percentages
    name = re.sub(r"\d+%", "", name)

    # Replace separators
    name = re.sub(r"[-_/|]+", " ", name)

    # Remove product codes at end
    name = re.sub(r"\b[a-z0-9]{6,}\b$", "", name)

    # Remove extra spaces
    name = re.sub(r"\s+", " ", name)

    return name.strip()

# ==========================================
# EXTRACT BRAND IF EMPTY
# ==========================================

def extract_brand(row):

    brand = clean_text(row["brand"])

    if brand != "":
        return brand

    words = clean_name(row["name_en"]).split()

    if len(words) == 0:
        return ""

    return words[0].title()

# ==========================================
# CLEAN DESCRIPTION
# ==========================================

def clean_description(desc):

    desc = clean_text(desc)

    patterns = [
        r"how to use:.*",
        r"ingredients:.*",
        r"طريقة الاستخدام:.*",
        r"كيفية الاستخدام:.*",
        r"مكونات:.*",
        r"contents hide.*"
    ]

    for p in patterns:
        desc = re.sub(
            p,
            "",
            desc,
            flags=re.IGNORECASE | re.DOTALL
        )

    # Remove duplicated sentences
    parts = []

    for sentence in desc.split("."):

        sentence = sentence.strip()

        if sentence and sentence not in parts:
            parts.append(sentence)

    desc = ". ".join(parts)

    desc = re.sub(r"\s+", " ", desc)

    return desc.strip()

# ==========================================
# KEEP FIRST IMAGE
# ==========================================

def first_image(img):

    if pd.isna(img):
        return ""

    img = str(img)

    if "|" in img:
        return img.split("|")[0].strip()

    if "," in img:
        return img.split(",")[0].strip()

    return img.strip()

# ==========================================
# APPLY CLEANING
# ==========================================

df["name_en"] = df["name_en"].apply(clean_name)

df["brand"] = df.apply(extract_brand, axis=1)

df["category"] = df["category"].apply(clean_text)

df["description"] = df["description"].apply(clean_description)

df["gallery_images"] = df["gallery_images"].apply(first_image)

df["price"] = pd.to_numeric(df["price"], errors="coerce")

# ==========================================
# REMOVE EMPTY NAMES
# ==========================================

df = df[df["name_en"] != ""]

# ==========================================
# REMOVE DUPLICATES
# ==========================================

df.drop_duplicates(
    subset=[
        "name_en",
        "brand",
        "price"
    ],
    inplace=True
)

# ==========================================
# FINAL ORDER
# ==========================================

df = df[
    [
        "pharmacy",
        "name_en",
        "brand",
        "category",
        "description",
        "gallery_images",
        "price",
        "currency"
    ]
]

# ==========================================
# SAVE
# ==========================================

os.makedirs(
    "downloads/aldawaaegy",
    exist_ok=True
)

df.to_csv(
    OUTPUT_FILE,
    index=False,
    encoding="utf-8-sig"
)

print()
print("Rows After:", len(df))
print("Saved:", OUTPUT_FILE)

"""******************
Normalization
******************

"""

import os
import pandas as pd

# ==========================================
# Files
# ==========================================

files = [
    "downloads/chefaa/chefaa_CLEAN.csv",
    "downloads/bloom/bloom_CLEAN.csv",
    "downloads/gardenia/gardenia_CLEAN.csv",
    "downloads/aldawaaegy/aldawaaegy_CLEAN.csv"
]

# ==========================================
# Final Schema
# ==========================================

final_columns = [

    "pharmacy",

    "name_ar",
    "name_en",

    "brand",
    "category",

    "description_ar",
    "description_en",
    "description",

    "gallery_images",

    "price",
    "currency"

]

# ==========================================
# Merge
# ==========================================

all_data = []

for file in files:

    print(f"Reading {file}")

    df = pd.read_csv(file, low_memory=False)

    # Add Missing Columns
    for col in final_columns:

        if col not in df.columns:

            df[col] = ""

    # ترتيب الأعمدة
    df = df[final_columns]

    all_data.append(df)

# ==========================================
# Combine
# ==========================================

master_df = pd.concat(
    all_data,
    ignore_index=True
)

print()
print("Total Rows:", len(master_df))

# ==========================================
# Save
# ==========================================

os.makedirs("downloads/master", exist_ok=True)

output_file = "downloads/master/master_clean.csv"

master_df.to_csv(
    output_file,
    index=False,
    encoding="utf-8-sig"
)

print()
print("Saved:", output_file)

"""# **normalized_name**"""

# ==========================================================
# INSTALL
# ==========================================================

!pip -q install rapidfuzz

# ==========================================================
# IMPORTS
# ==========================================================

import re
import html
import pandas as pd

from urllib.parse import unquote

# ==========================================================
# FILE
# ==========================================================

INPUT_FILE = "downloads/master/master_clean.csv"

OUTPUT_FILE = "downloads/master/master_matching.csv"

# ==========================================================
# READ
# ==========================================================

df = pd.read_csv(
    INPUT_FILE,
    low_memory=False
)

print("="*60)
print("MASTER DATA")
print("="*60)

print("Rows :",len(df))
print()

# ==========================================================
# CLEAN TEXT
# ==========================================================

def clean_text(text):

    if pd.isna(text):

        return ""

    text = str(text)

    text = unquote(text)

    text = html.unescape(text)

    text = text.lower()

    text = text.replace("\n"," ")

    text = text.replace("\r"," ")

    text = text.strip()

    text = re.sub(r"\s+"," ",text)

    return text

# ==========================================================
# BUILD SEARCH NAME
# ==========================================================

def build_search_name(name):

    text = clean_text(name)

    # إزالة الحجم
    text = re.sub(
        r"\b\d+(\.\d+)?\s*(ml|mg|gm|g|kg|mcg|oz|pcs|pc|tab|tabs|capsule|capsules|cap|مل|جم|قطعة)\b",
        " ",
        text
    )

    # إزالة النسبة
    text = re.sub(
        r"\d+(\.\d+)?%",
        " ",
        text
    )

    # توحيد الفواصل
    text = re.sub(
        r"[-_/(),+]",
        " ",
        text
    )

    # توحيد أشهر الكلمات
    replacements = {

        "roll-on":"roll on",

        "rollon":"roll on",

        "anti perspirant":"antiperspirant",

        "facewash":"face wash",

        "bodywash":"body wash",

        "mouth wash":"mouthwash",

        "spf50":"spf 50",

        "spf30":"spf 30"

    }

    for old,new in replacements.items():

        text = text.replace(old,new)

    text = re.sub(r"\s+"," ",text)

    return text.strip()

# ==========================================================
# SEARCH NAME
# ==========================================================

df["search_name"] = df["name_en"].apply(
    build_search_name
)

# ==========================================================
# CLEAN PRICE
# ==========================================================

df["price"] = pd.to_numeric(

    df["price"],

    errors="coerce"

)

# ==========================================================
# PRODUCT ID
# ==========================================================

df["product_id"] = range(
    1,
    len(df)+1
)

# ==========================================================
# MATCH COLUMNS
# ==========================================================

df["match_group"] = -1

df["match_score"] = 0.0

df["canonical_name"] = ""

# ==========================================================
# SAVE
# ==========================================================

df.to_csv(

    OUTPUT_FILE,

    index=False,

    encoding="utf-8-sig"

)

# ==========================================================
# REPORT
# ==========================================================

print("="*60)

print("DONE")

print("="*60)

print()

print("Rows :",len(df))

print()

print("Output :")

print(OUTPUT_FILE)

# ==========================================================
# CANDIDATE GENERATION
# ==========================================================

import pandas as pd

# ==========================================================
# FILES
# ==========================================================

INPUT_FILE = "downloads/master/master_matching.csv"
OUTPUT_FILE = "downloads/master/master_matching.csv"

# ==========================================================
# READ
# ==========================================================

df = pd.read_csv(INPUT_FILE, low_memory=False)

print("=" * 60)
print("CANDIDATE GENERATION")
print("=" * 60)

# ==========================================================
# CLEAN PRICE
# ==========================================================

df["price"] = pd.to_numeric(
    df["price"],
    errors="coerce"
)

# ==========================================================
# SORT BY PRICE
# ==========================================================

df = df.sort_values("price").reset_index(drop=True)

# ==========================================================
# BUILD CANDIDATES
# ==========================================================

candidate_pairs = []

PRICE_TOLERANCE = 5

for i in range(len(df)):

    p1 = df.at[i, "price"]

    if pd.isna(p1):
        continue

    for j in range(i + 1, len(df)):

        p2 = df.at[j, "price"]

        if pd.isna(p2):
            continue

        # لأن الداتا مرتبة حسب السعر
        if (p2 - p1) > PRICE_TOLERANCE:
            break

        candidate_pairs.append({

            "product_id_1": df.at[i, "product_id"],
            "product_id_2": df.at[j, "product_id"],

            "pharmacy_1": df.at[i, "pharmacy"],
            "pharmacy_2": df.at[j, "pharmacy"],

            "name_1": df.at[i, "search_name"],
            "name_2": df.at[j, "search_name"],

            "price_1": p1,
            "price_2": p2

        })

candidate_df = pd.DataFrame(candidate_pairs)

print()
print("Candidate Pairs :", len(candidate_df))

# ==========================================================
# SAVE
# ==========================================================

candidate_df.to_csv(
    "downloads/master/candidate_pairs.csv",
    index=False,
    encoding="utf-8-sig"
)

df.to_csv(
    OUTPUT_FILE,
    index=False,
    encoding="utf-8-sig"
)

print()
print("Saved:")
print("downloads/master/candidate_pairs.csv")
print("downloads/master/master_matching.csv")

# ==========================================================
# NAME MATCHING
# ==========================================================

import pandas as pd
from rapidfuzz import fuzz

# ==========================================================
# FILES
# ==========================================================

INPUT_FILE = "downloads/master/candidate_pairs.csv"

OUTPUT_FILE = "downloads/master/candidate_matches.csv"

# ==========================================================
# READ
# ==========================================================

df = pd.read_csv(INPUT_FILE, low_memory=False)

print("=" * 60)
print("NAME MATCHING")
print("=" * 60)

# ==========================================================
# SIMILARITY FUNCTION
# ==========================================================

def calculate_score(name1, name2):

    score1 = fuzz.token_set_ratio(name1, name2)

    score2 = fuzz.token_sort_ratio(name1, name2)

    score3 = fuzz.partial_ratio(name1, name2)

    score4 = fuzz.WRatio(name1, name2)

    final_score = (
        score1 * 0.35 +
        score2 * 0.25 +
        score3 * 0.15 +
        score4 * 0.25
    )

    return round(final_score, 2)

# ==========================================================
# MATCHING
# ==========================================================

scores = []
matches = []

MATCH_THRESHOLD = 94

for _, row in df.iterrows():

    score = calculate_score(
        str(row["name_1"]),
        str(row["name_2"])
    )

    scores.append(score)

    matches.append(score >= MATCH_THRESHOLD)

df["similarity_score"] = scores

df["is_match"] = matches

# ==========================================================
# SORT
# ==========================================================

df = df.sort_values(
    by="similarity_score",
    ascending=False
).reset_index(drop=True)

# ==========================================================
# REPORT
# ==========================================================

print()
print("Candidate Pairs :", len(df))
print("Matched Pairs   :", df["is_match"].sum())
print("Rejected Pairs  :", len(df) - df["is_match"].sum())

print()
print(df[
    [
        "name_1",
        "name_2",
        "similarity_score",
        "is_match"
    ]
].head(20))

# ==========================================================
# SAVE
# ==========================================================

df.to_csv(
    OUTPUT_FILE,
    index=False,
    encoding="utf-8-sig"
)

print()
print("Saved:")
print(OUTPUT_FILE)

# ==========================================================
# BUILD PRODUCT GROUPS
# ==========================================================

import pandas as pd

# ==========================================================
# FILES
# ==========================================================

MATCHES_FILE = "downloads/master/candidate_matches.csv"

MASTER_FILE = "downloads/master/master_matching.csv"

OUTPUT_FILE = "downloads/master/master_matching.csv"

# ==========================================================
# READ
# ==========================================================

matches = pd.read_csv(MATCHES_FILE)

master = pd.read_csv(MASTER_FILE)

print("=" * 60)
print("BUILD PRODUCT GROUPS")
print("=" * 60)

# ==========================================================
# UNION FIND
# ==========================================================

class UnionFind:

    def __init__(self):

        self.parent = {}

    def add(self, x):

        if x not in self.parent:

            self.parent[x] = x

    def find(self, x):

        if self.parent[x] != x:

            self.parent[x] = self.find(self.parent[x])

        return self.parent[x]

    def union(self, a, b):

        ra = self.find(a)

        rb = self.find(b)

        if ra != rb:

            self.parent[rb] = ra

# ==========================================================
# INITIALIZE
# ==========================================================

uf = UnionFind()

for pid in master["product_id"]:

    uf.add(pid)

# ==========================================================
# BUILD LINKS
# ==========================================================

links = matches[matches["is_match"] == True]

print("Matched Links :", len(links))

for _, row in links.iterrows():

    uf.union(

        int(row["product_id_1"]),

        int(row["product_id_2"])

    )

# ==========================================================
# CREATE GROUP IDS
# ==========================================================

group_map = {}

next_group = 1

groups = []

for pid in master["product_id"]:

    root = uf.find(pid)

    if root not in group_map:

        group_map[root] = next_group

        next_group += 1

    groups.append(group_map[root])

master["match_group"] = groups

# ==========================================================
# GROUP STATISTICS
# ==========================================================

group_stats = (

    master

    .groupby("match_group")

    .size()

    .reset_index(name="products")

)

master = master.merge(

    group_stats,

    on="match_group",

    how="left"

)

# ==========================================================
# REPORT
# ==========================================================

print()

print("Total Groups :", master["match_group"].nunique())

print()

print("Largest Groups")

print()

print(

    group_stats

    .sort_values(

        "products",

        ascending=False

    )

    .head(20)

)

# ==========================================================
# SAVE
# ==========================================================

master.to_csv(

    OUTPUT_FILE,

    index=False,

    encoding="utf-8-sig"

)

print()

print("Saved:")

print(OUTPUT_FILE)

# ==========================================================
# SELECT CANONICAL NAME
# ==========================================================

import re
import pandas as pd
from collections import Counter

# ==========================================================
# FILES
# ==========================================================

INPUT_FILE = "downloads/master/master_matching.csv"

OUTPUT_FILE = "downloads/master/master_matching.csv"

# ==========================================================
# READ
# ==========================================================

df = pd.read_csv(INPUT_FILE, low_memory=False)

print("=" * 60)
print("SELECT CANONICAL NAME")
print("=" * 60)

# ==========================================================
# PHARMACY PRIORITY
# ==========================================================

PHARMACY_PRIORITY = {
    "bloom": 4,
    "chefaa": 3,
    "gardenia": 2,
    "aldawaaegy": 1
}

# ==========================================================
# TOKENIZE
# ==========================================================

def tokenize(text):

    if pd.isna(text):
        return []

    text = str(text).lower()

    text = re.sub(r"[^a-z0-9 ]", " ", text)

    text = re.sub(r"\s+", " ", text).strip()

    return text.split()

# ==========================================================
# NAME SCORE
# ==========================================================

def calculate_name_score(name, common_words, pharmacy):

    score = 0

    tokens = tokenize(name)

    # عدد الكلمات
    score += len(tokens) * 2

    # الكلمات المشتركة
    for token in tokens:

        score += common_words.get(token, 0) * 5

    # أولوية الصيدلية
    score += PHARMACY_PRIORITY.get(str(pharmacy).lower(), 0) * 10

    # خصم لو الاسم فيه %
    if "%" in str(name):
        score -= 10

    # خصم لو فيه URL Encoding
    if "%d" in str(name).lower():
        score -= 30

    return score

# ==========================================================
# CREATE COLUMN
# ==========================================================

df["canonical_name"] = df["name_en"]

# ==========================================================
# PROCESS EACH GROUP
# ==========================================================

groups = df.groupby("match_group")

updated_groups = 0

for group_id, group in groups:

    if len(group) == 1:
        continue

    counter = Counter()

    for name in group["name_en"]:

        counter.update(tokenize(name))

    best_score = -1

    best_name = None

    for _, row in group.iterrows():

        score = calculate_name_score(

            row["name_en"],

            counter,

            row["pharmacy"]

        )

        if score > best_score:

            best_score = score

            best_name = row["name_en"]

    df.loc[

        df["match_group"] == group_id,

        "canonical_name"

    ] = best_name

    updated_groups += 1

# ==========================================================
# REPORT
# ==========================================================

print()

print("Groups Updated :", updated_groups)

print()

print(df[
    [
        "match_group",
        "pharmacy",
        "name_en",
        "canonical_name"
    ]
].head(30))

# ==========================================================
# SAVE
# ==========================================================

df.to_csv(

    OUTPUT_FILE,

    index=False,

    encoding="utf-8-sig"

)

print()

print("Saved:")

print(OUTPUT_FILE)

# ==========================================================
# APPLY CANONICAL NAMES
# ==========================================================

import pandas as pd

# ==========================================================
# FILES
# ==========================================================

INPUT_FILE = "downloads/master/master_matching.csv"

OUTPUT_FILE = "downloads/master/master_clean.csv"

# ==========================================================
# READ
# ==========================================================

df = pd.read_csv(INPUT_FILE, low_memory=False)

print("=" * 60)
print("APPLY CANONICAL NAMES")
print("=" * 60)

# ==========================================================
# REPLACE NAME
# ==========================================================

changed = (
    df["name_en"] != df["canonical_name"]
).sum()

df["name_en"] = df["canonical_name"]

# ==========================================================
# REMOVE TEMP COLUMNS
# ==========================================================

temp_columns = [

    "search_name",

    "match_group",

    "match_score",

    "canonical_name",

    "products"

]

for col in temp_columns:

    if col in df.columns:

        df.drop(columns=col, inplace=True)

# ==========================================================
# REMOVE DUPLICATES
# ==========================================================

df = df.drop_duplicates().reset_index(drop=True)

# ==========================================================
# SORT
# ==========================================================

sort_columns = []

if "pharmacy" in df.columns:
    sort_columns.append("pharmacy")

if "brand" in df.columns:
    sort_columns.append("brand")

if "name_en" in df.columns:
    sort_columns.append("name_en")

if len(sort_columns):

    df = df.sort_values(
        by=sort_columns
    ).reset_index(drop=True)

# ==========================================================
# SAVE
# ==========================================================

df.to_csv(

    OUTPUT_FILE,

    index=False,

    encoding="utf-8-sig"

)

# ==========================================================
# REPORT
# ==========================================================

print()

print("=" * 60)
print("FINISHED")
print("=" * 60)

print()

print("Rows :", len(df))

print()

print("Names Updated :", changed)

print()

print("Unique Products :", df["name_en"].nunique())

print()

print("Saved Successfully")

print()

print(OUTPUT_FILE)

# ==========================================================
# VALIDATION
# ==========================================================

import pandas as pd

# ==========================================================
# FILE
# ==========================================================

INPUT_FILE = "downloads/master/master_clean.csv"

# ==========================================================
# READ
# ==========================================================

df = pd.read_csv(
    INPUT_FILE,
    low_memory=False
)

print("="*60)
print("VALIDATION")
print("="*60)

# ==========================================================
# PRICE
# ==========================================================

df["price"] = pd.to_numeric(
    df["price"],
    errors="coerce"
)

# ==========================================================
# REPORT FOLDER
# ==========================================================

REPORT_FOLDER = "downloads/master/reports"

import os

os.makedirs(
    REPORT_FOLDER,
    exist_ok=True
)

# ==========================================================
# 1 SAME NAME DIFFERENT PRICE
# ==========================================================

price_report = []

for name, group in df.groupby("name_en"):

    prices = group["price"].dropna().unique()

    if len(prices) <= 1:
        continue

    if max(prices) - min(prices) > 20:

        price_report.append(group)

if len(price_report):

    price_report = pd.concat(price_report)

else:

    price_report = pd.DataFrame()

price_report.to_csv(

    REPORT_FOLDER + "/01_same_name_different_price.csv",

    index=False,

    encoding="utf-8-sig"

)

# ==========================================================
# 2 LARGE GROUPS
# ==========================================================

large_groups = (

    df

    .groupby("name_en")

    .size()

    .reset_index(name="count")

)

large_groups = large_groups[

    large_groups["count"] >= 5

]

large_groups.to_csv(

    REPORT_FOLDER + "/02_large_groups.csv",

    index=False,

    encoding="utf-8-sig"

)

# ==========================================================
# 3 MISSING BRAND
# ==========================================================

missing_brand = df[

    df["brand"]

    .fillna("")

    .astype(str)

    .str.strip()

    == ""

]

missing_brand.to_csv(

    REPORT_FOLDER + "/03_missing_brand.csv",

    index=False,

    encoding="utf-8-sig"

)

# ==========================================================
# 4 MISSING CATEGORY
# ==========================================================

missing_category = df[

    df["category"]

    .fillna("")

    .astype(str)

    .str.strip()

    == ""

]

missing_category.to_csv(

    REPORT_FOLDER + "/04_missing_category.csv",

    index=False,

    encoding="utf-8-sig"

)

# ==========================================================
# 5 DUPLICATE PRODUCTS
# ==========================================================

duplicates = df[

    df.duplicated(

        subset=[

            "pharmacy",

            "name_en",

            "price"

        ],

        keep=False

    )

]

duplicates.to_csv(

    REPORT_FOLDER + "/05_duplicates.csv",

    index=False,

    encoding="utf-8-sig"

)

# ==========================================================
# REPORT
# ==========================================================

print()

print("="*60)

print("REPORT")

print("="*60)

print()

print("Different Price :",len(price_report))

print("Large Groups :",len(large_groups))

print("Missing Brand :",len(missing_brand))

print("Missing Category :",len(missing_category))

print("Duplicates :",len(duplicates))

print()

print("Reports Saved In")

print(REPORT_FOLDER)



# ==========================================================
# FINAL CLEANUP
# ==========================================================

import pandas as pd

# ==========================================================
# FILE
# ==========================================================

INPUT_FILE = "downloads/master/master_clean.csv"
OUTPUT_FILE = "downloads/master/master_clean.csv"

# ==========================================================
# READ
# ==========================================================

df = pd.read_csv(INPUT_FILE, low_memory=False)

print("=" * 60)
print("FINAL CLEANUP")
print("=" * 60)

# ==========================================================
# COMPLETENESS SCORE
# ==========================================================

important_columns = [
    "brand",
    "category",
    "description",
    "description_en",
    "description_ar",
    "gallery_images"
]

for col in important_columns:

    if col not in df.columns:

        df[col] = ""

def completeness_score(row):

    score = 0

    for col in important_columns:

        value = str(row[col]).strip()

        if value != "" and value.lower() != "nan":

            score += 1

    return score

df["completeness"] = df.apply(
    completeness_score,
    axis=1
)

# ==========================================================
# KEEP BEST RECORD
# ==========================================================

before_rows = len(df)

df = (

    df

    .sort_values(
        "completeness",
        ascending=False
    )

    .drop_duplicates(

        subset=[

            "pharmacy",
            "name_en",
            "price"

        ],

        keep="first"

    )

)

after_rows = len(df)

removed = before_rows - after_rows

# ==========================================================
# REMOVE TEMP COLUMN
# ==========================================================

df.drop(
    columns="completeness",
    inplace=True
)

# ==========================================================
# PRODUCTS FOUND IN MULTIPLE PHARMACIES
# ==========================================================

shared_products = (

    df

    .groupby("name_en")["pharmacy"]

    .nunique()

)

shared_products = shared_products[
    shared_products > 1
]

# ==========================================================
# REPORT
# ==========================================================

print()

print("=" * 60)
print("REPORT")
print("=" * 60)

print()

print(f"Rows Before : {before_rows}")
print(f"Rows After  : {after_rows}")

print()

print(f"Removed Duplicate Products : {removed}")

print()

print(f"Products Found In More Than One Pharmacy : {len(shared_products)}")

print()

for pharmacy in sorted(df["pharmacy"].unique()):

    count = (

        df[df["pharmacy"] == pharmacy]

        .shape[0]

    )

    print(f"{pharmacy:<15} : {count}")

# ==========================================================
# SAVE
# ==========================================================

df.to_csv(

    OUTPUT_FILE,

    index=False,

    encoding="utf-8-sig"

)

print()

print("Saved Successfully")

print(OUTPUT_FILE)

# ==========================================================
# BRAND NORMALIZATION
# ==========================================================

import re
import pandas as pd
from collections import Counter

# ==========================================================
# FILE
# ==========================================================

INPUT_FILE = "downloads/master/master_clean.csv"
OUTPUT_FILE = "downloads/master/master_clean.csv"

# ==========================================================
# READ
# ==========================================================

df = pd.read_csv(INPUT_FILE, low_memory=False)

print("=" * 60)
print("BRAND NORMALIZATION")
print("=" * 60)

# ==========================================================
# CREATE BRAND COLUMN
# ==========================================================

if "brand" not in df.columns:
    df["brand"] = ""

# ==========================================================
# CLEAN BRAND
# ==========================================================

def clean_brand(text):

    if pd.isna(text):
        return ""

    text = str(text)

    text = text.strip()

    text = re.sub(r"\s+", " ", text)

    text = re.sub(r"[^\w\s&+.'/-]", "", text)

    return text

# ==========================================================
# ENGLISH CHECK
# ==========================================================

def is_english(text):

    if text == "":
        return False

    return bool(re.search(r"[A-Za-z]", text))

# ==========================================================
# NORMALIZE CASE
# ==========================================================

def normalize_key(text):

    text = clean_brand(text)

    return text.lower()

# ==========================================================
# DISPLAY FORMAT
# ==========================================================

def display_brand(text):

    text = clean_brand(text)

    return text.title()

# ==========================================================
# CLEAN COLUMN
# ==========================================================

df["brand"] = df["brand"].fillna("").apply(clean_brand)

# ==========================================================
# NORMALIZE BRANDS
# ==========================================================

updated = 0

for product_name, group in df.groupby("name_en"):

    english_brands = []

    original_forms = {}

    for brand in group["brand"]:

        if not is_english(brand):
            continue

        key = normalize_key(brand)

        english_brands.append(key)

        if key not in original_forms:

            original_forms[key] = display_brand(brand)

    if len(english_brands) == 0:
        continue

    counter = Counter(english_brands)

    best_key = sorted(

        counter.items(),

        key=lambda x: (

            x[1],
            len(x[0])

        ),

        reverse=True

    )[0][0]

    best_brand = original_forms[best_key]

    mask = df["name_en"] == product_name

    changed = (df.loc[mask, "brand"] != best_brand).sum()

    updated += changed

    df.loc[mask, "brand"] = best_brand

# ==========================================================
# REMOVE EXTRA SPACES
# ==========================================================

df["brand"] = (

    df["brand"]

    .astype(str)

    .str.replace(r"\s+", " ", regex=True)

    .str.strip()

)

# ==========================================================
# REPORT
# ==========================================================

print()

print("=" * 60)
print("REPORT")
print("=" * 60)

print()

print("Rows :", len(df))

print()

print("Brands Updated :", updated)

print()

print("Unique Brands :", df["brand"].nunique())

print()

print(df["brand"].value_counts().head(20))

# ==========================================================
# SAVE
# ==========================================================

df.to_csv(

    OUTPUT_FILE,

    index=False,

    encoding="utf-8-sig"

)

print()

print("Saved Successfully")

print(OUTPUT_FILE)



# ==========================================================
# CATEGORY NORMALIZATION
# ==========================================================

import re
import pandas as pd
from collections import Counter

# ==========================================================
# FILE
# ==========================================================

INPUT_FILE = "downloads/master/master_clean.csv"
OUTPUT_FILE = "downloads/master/master_clean.csv"

# ==========================================================
# READ
# ==========================================================

df = pd.read_csv(INPUT_FILE, low_memory=False)

print("=" * 60)
print("CATEGORY NORMALIZATION")
print("=" * 60)

# ==========================================================
# CREATE COLUMN
# ==========================================================

if "category" not in df.columns:
    df["category"] = ""

# ==========================================================
# CLEAN CATEGORY
# ==========================================================

def clean_category(text):

    if pd.isna(text):
        return ""

    text = str(text)

    text = text.strip()

    text = text.lower()

    text = text.replace("_", " ")
    text = text.replace("-", " ")
    text = text.replace("&", " and ")

    text = re.sub(r"\s+", " ", text)

    return text

# ==========================================================
# ENGLISH CHECK
# ==========================================================

def is_english(text):

    if text == "":
        return False

    return bool(re.search(r"[A-Za-z]", text))

# ==========================================================
# DISPLAY FORMAT
# ==========================================================

def display_category(text):

    words = clean_category(text).split()

    return " ".join(word.capitalize() for word in words)

# ==========================================================
# CATEGORY DICTIONARY
# ==========================================================

CATEGORY_MAP = {

    "skin care": "Skin Care",
    "skincare": "Skin Care",

    "hair care": "Hair Care",
    "haircare": "Hair Care",

    "oral care": "Oral Care",
    "oralcare": "Oral Care",

    "baby care": "Baby Care",
    "baby": "Baby Care",

    "body care": "Body Care",

    "face care": "Face Care",

    "makeup": "Makeup",
    "make up": "Makeup",

    "sun care": "Sun Care",

    "eye care": "Eye Care",

    "men care": "Men Care",

    "women care": "Women Care",

    "vitamins": "Vitamins",
    "vitamins supplements": "Vitamins & Supplements",
    "vitamins and supplements": "Vitamins & Supplements",

    "medical devices": "Medical Devices",

    "mother and baby": "Mother & Baby",
    "mom baby": "Mother & Baby",

    "fragrance": "Fragrance",
    "perfumes": "Fragrance",

    "sexual wellness": "Sexual Wellness"

}

# ==========================================================
# CLEAN COLUMN
# ==========================================================

df["category"] = df["category"].fillna("").astype(str)

updated = 0

# ==========================================================
# NORMALIZE
# ==========================================================

for product_name, group in df.groupby("name_en"):

    categories = []

    original = {}

    for category in group["category"]:

        if not is_english(category):
            continue

        key = clean_category(category)

        if key in CATEGORY_MAP:
            display = CATEGORY_MAP[key]
        else:
            display = display_category(key)

        categories.append(display)

        original[display.lower()] = display

    if len(categories) == 0:
        continue

    counter = Counter(categories)

    best_category = sorted(

        counter.items(),

        key=lambda x: (

            x[1],
            len(x[0])

        ),

        reverse=True

    )[0][0]

    mask = df["name_en"] == product_name

    changed = (

        df.loc[mask, "category"] != best_category

    ).sum()

    updated += changed

    df.loc[mask, "category"] = best_category

# ==========================================================
# FINAL CLEAN
# ==========================================================

df["category"] = (

    df["category"]

    .astype(str)

    .str.replace(r"\s+", " ", regex=True)

    .str.strip()

)

# ==========================================================
# REPORT
# ==========================================================

print()

print("=" * 60)
print("REPORT")
print("=" * 60)

print()

print("Rows :", len(df))

print()

print("Categories Updated :", updated)

print()

print("Unique Categories :", df["category"].nunique())

print()

print(df["category"].value_counts().head(30))

# ==========================================================
# SAVE
# ==========================================================

df.to_csv(

    OUTPUT_FILE,

    index=False,

    encoding="utf-8-sig"

)

print()

print("Saved Successfully")

print(OUTPUT_FILE)



# ==========================================================
# GENERATE CATEGORIES TABLE
# ==========================================================

import pandas as pd

# ==========================================================
# FILES
# ==========================================================

MASTER_FILE = "downloads/master/master_clean.csv"

CATEGORY_FILE = "downloads/master/categories.csv"

OUTPUT_MASTER = "downloads/master/master_clean.csv"

# ==========================================================
# READ
# ==========================================================

df = pd.read_csv(
    MASTER_FILE,
    low_memory=False
)

print("=" * 60)
print("GENERATE CATEGORY TABLE")
print("=" * 60)

# ==========================================================
# CLEAN CATEGORY
# ==========================================================

df["category"] = (

    df["category"]

    .fillna("")

    .astype(str)

    .str.strip()

)

# Remove Empty Categories
df = df[df["category"] != ""]

# ==========================================================
# UNIQUE CATEGORIES
# ==========================================================

categories = (

    df["category"]

    .drop_duplicates()

    .sort_values()

    .reset_index(drop=True)

)

category_df = pd.DataFrame({

    "category_id": range(1, len(categories) + 1),

    "name": categories,

    "description": categories + " products"

})

# ==========================================================
# CREATE MAPPING
# ==========================================================

category_map = dict(

    zip(

        category_df["name"],

        category_df["category_id"]

    )

)

# ==========================================================
# ADD CATEGORY ID
# ==========================================================

master = pd.read_csv(
    MASTER_FILE,
    low_memory=False
)

master["category_id"] = (

    master["category"]

    .map(category_map)

)

# ==========================================================
# SAVE
# ==========================================================

category_df.to_csv(

    CATEGORY_FILE,

    index=False,

    encoding="utf-8-sig"

)

master.to_csv(

    OUTPUT_MASTER,

    index=False,

    encoding="utf-8-sig"

)

# ==========================================================
# REPORT
# ==========================================================

print()

print("=" * 60)
print("REPORT")
print("=" * 60)

print()

print(f"Total Categories : {len(category_df)}")

print()

print("Top 20 Categories")

print()

print(

    master["category"]

    .value_counts()

    .head(20)

)

print()

print("Category Table Preview")

print()

print(

    category_df.head(20)

)

print()

print("=" * 60)

print("FILES CREATED")

print("=" * 60)

print()

print(CATEGORY_FILE)

print()

print(OUTPUT_MASTER)

print()

print("Done Successfully ✅")



# ==========================================================
# INSTALL
# ==========================================================

!pip install sqlalchemy psycopg2-binary pandas -q

# ==========================================================
# IMPORTS
# ==========================================================

import pandas as pd
from sqlalchemy import create_engine, text



DATABASE_URL = ""

# ==========================================================
# FILE
# ==========================================================

CSV_FILE = "downloads/master/categories.csv"

# ==========================================================
# READ CSV
# ==========================================================

df = pd.read_csv(CSV_FILE)

print("="*60)
print("Categories :", len(df))
print("="*60)

# ==========================================================
# CONNECT
# ==========================================================

engine = create_engine(DATABASE_URL)

# ==========================================================
# INSERT
# ==========================================================

with engine.begin() as conn:

    # حذف البيانات القديمة
    conn.execute(
        text("DELETE FROM drug_categories")
    )

    # Reset Sequence
    conn.execute(
        text(
            """
            ALTER SEQUENCE drug_categories_id_seq
            RESTART WITH 1
            """
        )
    )

    # Insert
    for _, row in df.iterrows():

        conn.execute(

            text("""

            INSERT INTO drug_categories
            (
                id,
                name,
                description
            )

            VALUES
            (
                :id,
                :name,
                :description
            )

            """),

            {

                "id": int(row["category_id"]),

                "name": row["name"],

                "description": row["description"]

            }

        )

# ==========================================================
# REPORT
# ==========================================================

print()

print("="*60)
print("UPLOAD FINISHED")
print("="*60)

print()

print("Inserted Categories :", len(df))



# ==========================================================
# INSTALL
# ==========================================================

!pip install sqlalchemy psycopg2-binary pandas -q

# ==========================================================
# IMPORTS
# ==========================================================

import os
import re
import html
import shutil
import pandas as pd

from urllib.parse import unquote

from sqlalchemy import create_engine
from sqlalchemy import text

# ==========================================================
# DATABASE
# ==========================================================

DATABASE_URL = "postgresql://YOUR_CONNECTION_STRING"

# ==========================================================
# FILES
# ==========================================================

MASTER_FILE = "downloads/master/master_clean.csv"

WORKING_FILE = "downloads/master/drugs_prepared.csv"

# ==========================================================
# CREATE WORKING COPY
# ==========================================================

shutil.copy(
    MASTER_FILE,
    WORKING_FILE
)

print("="*60)
print("Working Copy Created")
print("="*60)

print(WORKING_FILE)

# ==========================================================
# READ
# ==========================================================

df = pd.read_csv(
    WORKING_FILE,
    low_memory=False
)

print()

print("Rows :",len(df))

# ==========================================================
# CREATE MISSING COLUMNS
# ==========================================================

new_columns=[

    "drug_name",

    "strength",

    "dosage_form",

    "active_substance",

    "manufacturer",

    "image_url"

]

for col in new_columns:

    if col not in df.columns:

        df[col]=""

# ==========================================================
# IMAGE
# ==========================================================

if "gallery_images" in df.columns:

    df["image_url"]=df["gallery_images"]

# ==========================================================
# MANUFACTURER
# ==========================================================

if "brand" in df.columns:

    df["manufacturer"]=df["brand"]

# ==========================================================
# CLEAN TEXT
# ==========================================================

def clean_text(text):

    if pd.isna(text):

        return ""

    text=str(text)

    text=unquote(text)

    text=html.unescape(text)

    text=text.strip()

    text=re.sub(r"\s+"," ",text)

    return text

# ==========================================================
# CLEAN NAME
# ==========================================================

df["name_en"]=df["name_en"].apply(
    clean_text
)

# ==========================================================
# DOSAGE FORMS
# ==========================================================

DOSAGE_FORMS=[

    "tablet",
    "tablets",

    "capsule",
    "capsules",

    "cream",

    "gel",

    "ointment",

    "spray",

    "drops",

    "drop",

    "syrup",

    "suspension",

    "solution",

    "powder",

    "patch",

    "foam",

    "lotion",

    "mouthwash",

    "mouth wash",

    "shampoo",

    "soap",

    "oil",

    "suppository",

    "ampoule",

    "ampoules",

    "vial",

    "inhaler",

    "stick",

    "roll on",

    "roll-on",

    "rollon"

]

# ==========================================================
# STRENGTH PATTERNS
# ==========================================================

STRENGTH_PATTERNS=[

r"\d+(\.\d+)?\s?mg",

r"\d+(\.\d+)?\s?gm",

r"\d+(\.\d+)?\s?g",

r"\d+(\.\d+)?\s?mcg",

r"\d+(\.\d+)?\s?kg",

r"\d+(\.\d+)?\s?ml",

r"\d+(\.\d+)?\s?l",

r"\d+(\.\d+)?\s?iu",

r"\d+(\.\d+)?\s?meq",

r"\d+(\.\d+)?\s?mmol",

r"\d+(\.\d+)?\s?%",

r"\d+/\d+\s?mg",

r"\d+/\d+\s?mcg",

r"\d+/\d+\s?ml"

]

print()

print("="*60)

print("Preparation Finished")

print("="*60)

# ==========================================================
# EXTRACT STRENGTH
# ==========================================================

def extract_strength(text):

    text=clean_text(text)

    for pattern in STRENGTH_PATTERNS:

        match=re.search(

            pattern,

            text,

            flags=re.IGNORECASE

        )

        if match:

            return match.group(0)

    return ""

# ==========================================================
# EXTRACT DOSAGE FORM
# ==========================================================

def extract_dosage_form(text):

    text=clean_text(text).lower()

    for form in sorted(

        DOSAGE_FORMS,

        key=len,

        reverse=True

    ):

        if form in text:

            return form.title()

    return ""

# ==========================================================
# REMOVE EXTRACTED INFO
# ==========================================================

def build_drug_name(text):

    text=clean_text(text)

    # Remove Strength
    for pattern in STRENGTH_PATTERNS:

        text=re.sub(

            pattern,

            " ",

            text,

            flags=re.IGNORECASE

        )

    # Remove Dosage Form
    for form in DOSAGE_FORMS:

        text=re.sub(

            re.escape(form),

            " ",

            text,

            flags=re.IGNORECASE

        )

    # Remove duplicate spaces
    text=re.sub(r"\s+"," ",text)

    return text.strip()

# ==========================================================
# APPLY EXTRACTION
# ==========================================================

df["strength"]=df["name_en"].apply(
    extract_strength
)

df["dosage_form"]=df["name_en"].apply(
    extract_dosage_form
)

df["drug_name"]=df["name_en"].apply(
    build_drug_name
)

print()

print("="*60)

print("Extraction Finished")

print("="*60)

print()

print(

df[
[
"name_en",
"drug_name",
"strength",
"dosage_form"
]

].head(20)

)

# ==========================================================
# CLEAN DRUG NAME
# ==========================================================

REMOVE_WORDS = [

    "pcs",
    "piece",
    "pieces",
    "pack",
    "offer",
    "offers",
    "free",
    "new",
    "original",
    "buy",
    "save",
    "gift",
    "promo"

]

def clean_drug_name(name):

    name = clean_text(name)

    # Remove Strength
    for pattern in STRENGTH_PATTERNS:

        name = re.sub(
            pattern,
            " ",
            name,
            flags=re.IGNORECASE
        )

    # Remove Dosage Form
    for form in sorted(DOSAGE_FORMS, key=len, reverse=True):

        name = re.sub(
            re.escape(form),
            " ",
            name,
            flags=re.IGNORECASE
        )

    # Remove Marketing Words
    for word in REMOVE_WORDS:

        name = re.sub(

            r"\b" + re.escape(word) + r"\b",

            " ",

            name,

            flags=re.IGNORECASE

        )

    # Remove Empty Brackets
    name = re.sub(r"\(\s*\)", " ", name)

    # Remove Symbols
    name = re.sub(r"[-_,+/]", " ", name)

    # Remove Extra Spaces
    name = re.sub(r"\s+", " ", name)

    return name.strip()

# ==========================================================
# APPLY
# ==========================================================

df["drug_name"] = df["drug_name"].apply(
    clean_drug_name
)

# ==========================================================
# REMOVE EMPTY
# ==========================================================

df = df[
    df["drug_name"] != ""
]

# ==========================================================
# SCORE
# ==========================================================

important = [

    "description",

    "manufacturer",

    "image_url",

    "strength",

    "dosage_form"

]

for col in important:

    if col not in df.columns:

        df[col] = ""

def completeness_score(row):

    score = 0

    for col in important:

        value = str(row[col]).strip()

        if value != "" and value.lower() != "nan":

            score += 1

    return score

df["score"] = df.apply(
    completeness_score,
    axis=1
)

# ==========================================================
# KEEP BEST RECORD
# ==========================================================

before = len(df)

df = (

    df

    .sort_values(

        "score",

        ascending=False

    )

    .drop_duplicates(

        subset=["drug_name"],

        keep="first"

    )

    .reset_index(drop=True)

)

after = len(df)

removed = before - after

# ==========================================================
# PREPARE FINAL TABLE
# ==========================================================

drugs = pd.DataFrame()

drugs["category_id"] = df["category_id"]

drugs["name"] = df["drug_name"]

drugs["manufacturer"] = df["manufacturer"]

drugs["description"] = df["description"]

drugs["image_url"] = df["image_url"]

drugs["strength"] = df["strength"]

drugs["dosage_form"] = df["dosage_form"]

drugs["active_substance"] = ""

# ==========================================================
# REMOVE DUPLICATE NAMES
# ==========================================================

drugs = (

    drugs

    .drop_duplicates(

        subset=["name"]

    )

    .reset_index(drop=True)

)

# ==========================================================
# SAVE
# ==========================================================

READY_FILE = "downloads/master/drugs_ready.csv"

drugs.to_csv(

    READY_FILE,

    index=False,

    encoding="utf-8-sig"

)

# ==========================================================
# REPORT
# ==========================================================

print()

print("=" * 60)

print("DRUGS PREPARATION")

print("=" * 60)

print()

print("Original Products :", before)

print("Unique Drugs :", len(drugs))

print("Duplicates Removed :", removed)

print()

print("Strength Extracted :",

      (drugs["strength"] != "").sum())

print("Dosage Form Extracted :",

      (drugs["dosage_form"] != "").sum())

print()

print("Preview")

print()

print(

    drugs.head(20)

)

print()

print("Saved")

print(READY_FILE)

# ==========================================================
# UPLOAD DRUGS TO NEON DATABASE
# ==========================================================

import pandas as pd
from sqlalchemy import create_engine, text

# ==========================================================
# DATABASE
# ==========================================================

DATABASE_URL = ""

# ==========================================================
# FILE
# ==========================================================

READY_FILE = "downloads/master/drugs_ready.csv"

# ==========================================================
# READ
# ==========================================================

df = pd.read_csv(
    READY_FILE,
    low_memory=False
)

print("=" * 60)
print("UPLOAD DRUGS")
print("=" * 60)

print()

print("Rows To Upload :", len(df))

# ==========================================================
# CONNECT
# ==========================================================

engine = create_engine(
    DATABASE_URL,
    pool_pre_ping=True
)

# ==========================================================
# CLEAN DATA
# ==========================================================

df = df.fillna("")

inserted = 0
failed = 0

# ==========================================================
# UPLOAD
# ==========================================================

with engine.begin() as conn:

    for _, row in df.iterrows():

        try:

            conn.execute(

                text("""

                INSERT INTO drugs
                (

                    category_id,
                    name,
                    manufacturer,
                    description,
                    image_url,
                    active_substance,
                    dosage_form,
                    strength

                )

                VALUES
                (

                    :category_id,
                    :name,
                    :manufacturer,
                    :description,
                    :image_url,
                    :active_substance,
                    :dosage_form,
                    :strength

                )

                """),

                {

                    "category_id":

                    None if row["category_id"] == ""

                    else int(row["category_id"]),

                    "name":

                    row["name"],

                    "manufacturer":

                    row["manufacturer"],

                    "description":

                    row["description"],

                    "image_url":

                    row["image_url"],

                    "active_substance":

                    row["active_substance"],

                    "dosage_form":

                    row["dosage_form"],

                    "strength":

                    row["strength"]

                }

            )

            inserted += 1

        except Exception as e:

            failed += 1

            print()

            print("=" * 40)

            print("FAILED")

            print("=" * 40)

            print()

            print(row["name"])

            print()

            print(e)

# ==========================================================
# VERIFY
# ==========================================================

with engine.connect() as conn:

    total = conn.execute(

        text(

            "SELECT COUNT(*) FROM drugs"

        )

    ).scalar()

# ==========================================================
# REPORT
# ==========================================================

print()

print("=" * 60)

print("UPLOAD REPORT")

print("=" * 60)

print()

print("Rows In CSV        :", len(df))

print("Inserted           :", inserted)

print("Failed             :", failed)

print("Rows In Database   :", total)

print()

print("Success Rate : {:.2f}%".format(

    inserted / len(df) * 100

))

print()

print("Finished Successfully ✅")

# ==========================================================
# INSTALL
# ==========================================================

!pip install sqlalchemy psycopg2-binary pandas -q

# ==========================================================
# IMPORTS
# ==========================================================

import pandas as pd
from sqlalchemy import create_engine, text

# ==========================================================
# DATABASE
# ==========================================================

DATABASE_URL = "postgresql://neondb_owner:npg_Gi2nkbKme4gx@ep-spring-sound-atfc1f55-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

# ==========================================================
# FILE
# ==========================================================

MASTER_FILE = "downloads/master/master_clean.csv"

# ==========================================================
# READ MASTER
# ==========================================================

master = pd.read_csv(
    MASTER_FILE,
    low_memory=False
)

print("=" * 60)
print("MASTER DATA")
print("=" * 60)

print("Rows :", len(master))

# ==========================================================
# CONNECT
# ==========================================================

engine = create_engine(
    DATABASE_URL,
    pool_pre_ping=True
)

# ==========================================================
# LOAD DRUGS
# ==========================================================

with engine.connect() as conn:

    drugs = pd.read_sql(

        text("""

        SELECT

            id,
            LOWER(TRIM(name)) AS name

        FROM drugs

        """),

        conn

    )

# ==========================================================
# LOAD PHARMACIES
# ==========================================================

with engine.connect() as conn:

    pharmacies = pd.read_sql(

        text("""

        SELECT

            id,
            LOWER(TRIM(name)) AS name

        FROM pharmacies

        """),

        conn

    )

# ==========================================================
# DRUG MAP
# ==========================================================

drug_map = dict(

    zip(

        drugs["name"],

        drugs["id"]

    )

)

# ==========================================================
# PHARMACY MAP
# ==========================================================

pharmacy_alias = {

    "chefaa": "chefaa",

    "aldawaaegy": "el dawaa",

    "bloom": "bloom",

    "gardenia": "gardenia"

}

pharmacy_map = dict(

    zip(

        pharmacies["name"],

        pharmacies["id"]

    )

)

# ==========================================================
# REMOVE DUPLICATES
# ==========================================================

master = (

    master

    .drop_duplicates(

        subset=[

            "pharmacy",

            "name_en"

        ]

    )

    .reset_index(drop=True)

)

# ==========================================================
# INSERT
# ==========================================================

inserted = 0

missing_drug = 0

missing_pharmacy = 0

failed = 0

seen = set()

with engine.begin() as conn:

    for _, row in master.iterrows():

        drug_name = str(

            row["name_en"]

        ).strip().lower()

        pharmacy_name = str(

            row["pharmacy"]

        ).strip().lower()

        pharmacy_name = pharmacy_alias.get(

            pharmacy_name,

            pharmacy_name

        )

        drug_id = drug_map.get(

            drug_name

        )

        pharmacy_id = pharmacy_map.get(

            pharmacy_name

        )

        if drug_id is None:

            missing_drug += 1

            continue

        if pharmacy_id is None:

            missing_pharmacy += 1

            continue

        pair = (

            pharmacy_id,

            drug_id

        )

        if pair in seen:

            continue

        seen.add(pair)

        try:

            conn.execute(

                text("""

                INSERT INTO pharmacy_inventory

                (

                    pharmacy_id,

                    drug_id,

                    quantity,

                    minimum_stock,

                    price,

                    last_updated

                )

                VALUES

                (

                    :pharmacy_id,

                    :drug_id,

                    :quantity,

                    :minimum_stock,

                    :price,

                    NOW()

                )

                """),

                {

                    "pharmacy_id": pharmacy_id,

                    "drug_id": drug_id,

                    "quantity": 100,

                    "minimum_stock": 100,

                    "price":

                    float(row["price"])

                    if pd.notna(row["price"])

                    else None

                }

            )

            inserted += 1

        except Exception as e:

            failed += 1

            print()

            print("=" * 40)

            print("FAILED")

            print("=" * 40)

            print()

            print(row["name_en"])

            print(e)

# ==========================================================
# VERIFY
# ==========================================================

with engine.connect() as conn:

    total = conn.execute(

        text("""

        SELECT COUNT(*)

        FROM pharmacy_inventory

        """)

    ).scalar()

# ==========================================================
# REPORT
# ==========================================================

print()

print("=" * 60)

print("UPLOAD REPORT")

print("=" * 60)

print()

print("Rows In Master         :", len(master))

print("Inserted              :", inserted)

print("Missing Drugs         :", missing_drug)

print("Missing Pharmacies    :", missing_pharmacy)

print("Failed Inserts        :", failed)

print("Rows In Database      :", total)

print()

print("Finished Successfully ✅")

"""=================================================================
Staging Storage
=================================================================
"""

import boto3

s3 = boto3.client(
    service_name="s3",
    endpoint_url="https://s3.us-east-005.backblazeb2.com",
    aws_access_key_id="005bba81d4d65f90000000001",
    aws_secret_access_key="K005UppmkxkYcgqaGDNxszdlDZi3mO4"
)

s3.upload_file(
    "hair-care.csv",
    "DEPI-Staging-CleanData",
    "inventory/hair-care.csv"
)

print("Uploaded Successfully")

response = s3.list_objects_v2(
    Bucket="DEPI-Staging-CleanData"
)

for obj in response.get("Contents", []):
    print(obj["Key"])

s3.delete_object(
    Bucket="DEPI-Staging-CleanData",
    Key="inventory/hair-care.csv"
)

print("Deleted Successfully")